---
- name : This playbook will run windows update
  hosts: all
  vars:
    patches:
      - windows10.0-kb4019472-x64_delta_c876f9bcf50eeec4520534e69c0b9a227c29f57c.msu


  tasks:
  - name: Copy accross HotFixes 
    win_copy:
      src: "/var/tmp/{{ item }}"
      dest: C:\
    with_items: "{{ patches }}"

  - name: Install HotFixes 
    win_hotfix:
      #hotfix_identifier: "{{ item }}"
      #source: C:\windows8.1-kb4344147-x64_776ef21945d613cf0eb93a7b3f5e3af61fef83b0.msu
      source: C:\{{ item }}
      state: present
    with_items: "{{ patches }}"
    register: hotfix_install

